In [1]:
import numpy as np

In [2]:
k = 1
N = 5
n = np.arange(0,N)
np.exp(1j * 2. * np.pi * k * n/N)

array([ 1.        +0.j        ,  0.30901699+0.95105652j,
       -0.80901699+0.58778525j, -0.80901699-0.58778525j,
        0.30901699-0.95105652j])

In [3]:
def genComplexSine(k, N):
    """
    Inputs:
        k (integer) = frequency index of the complex sinusoid of the DFT
        N (integer) = length of complex sinusoid in samples
    Output:
        The function should return a numpy array
        cSine (numpy array) = The generated complex sinusoid (length N)
    """
    n = np.arange(0,N)
    return np.conjugate(np.exp(1j * 2. * np.pi * k * n/N))

In [21]:
x = np.array([1,2,3,4])

x = x.astype(complex)
N = len(x)
X = np.zeros(N,dtype=complex)
k = np.arange(N)
k = k.reshape(4,1)

X = np.sum(x*genComplexSine(k,N),axis=1)

In [26]:
x_inv = np.sum(X*np.conjugate(genComplexSine(k,N))/N,axis=1)

In [28]:
np.allclose(x,x_inv)

True

In [16]:
def DFT(x):
    """
    Input:
        x (numpy array) = input sequence of length N
    Output:
        The function should return a numpy array of length N
        X (numpy array) = The N point DFT of the input sequence x
    """
    x = x.astype(complex)
    N = len(x)
    X = np.zeros(N,dtype=complex)
    for k in range(N):
        complex_sine = genComplexSine(k,N)
        X[k] = np.sum(x*complex_sine)
    return X

array([[0, 0, 0, 0],
       [0, 1, 2, 3],
       [0, 2, 4, 6],
       [0, 3, 6, 9]])

In [9]:
genComplexSine(k,N)

array([1.0000000e+00-0.0000000e+00j, 6.1232340e-17-1.0000000e+00j,
       1.0000000e+00+2.4492936e-16j, 5.5109106e-16-1.0000000e+00j])